import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "LexiReview Terms of Service. Terms and conditions governing use of the LexiReview AI contract management platform.",
  alternates: { canonical: "https://lexireview.in/terms" },
};

const lastUpdated = "30 March 2026";

export default function TermsOfServicePage() {
  return (
    <section className="pt-32 pb-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto prose prose-slate prose-headings:font-heading prose-headings:tracking-tight prose-a:text-blue-600">
        <h1 className="text-4xl font-heading font-black tracking-[-0.03em]">
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground">
          Last updated: {lastUpdated}
        </p>

        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and
          use of the LexiReview platform operated by LexiDraft Technologies
          (&quot;Company&quot;, &quot;we&quot;, &quot;us&quot;). By accessing or
          using LexiReview, you agree to be bound by these Terms.
        </p>

        <h2>1. Definitions</h2>
        <ul>
          <li><strong>&quot;Platform&quot;</strong> means the LexiReview website (lexireview.in), web application (app.lexireview.in), APIs, and related services.</li>
          <li><strong>&quot;User&quot;</strong> means any individual or entity that creates an account or uses the Platform.</li>
          <li><strong>&quot;Content&quot;</strong> means contracts, documents, data, and any materials uploaded to or generated by the Platform.</li>
          <li><strong>&quot;Credits&quot;</strong> means the review credits allocated under your subscription plan.</li>
        </ul>

        <h2>2. Eligibility and Account Registration</h2>
        <ul>
          <li>You must be at least 18 years old and legally competent to enter into a binding agreement under the Indian Contract Act, 1872.</li>
          <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
          <li>You must provide accurate and complete registration information.</li>
          <li>One person or entity may not maintain multiple free accounts.</li>
        </ul>

        <h2>3. Use of the Platform</h2>
        <h3>3.1 Permitted Use</h3>
        <p>
          You may use LexiReview for lawful contract review, generation,
          management, and compliance purposes in accordance with your
          subscription plan.
        </p>
        <h3>3.2 Prohibited Use</h3>
        <p>You shall not:</p>
        <ul>
          <li>Use the Platform for any unlawful purpose or in violation of any applicable law.</li>
          <li>Reverse-engineer, decompile, or attempt to extract the source code of the Platform or its AI models.</li>
          <li>Share account credentials with unauthorised third parties.</li>
          <li>Upload malicious code, viruses, or harmful content.</li>
          <li>Attempt to circumvent usage limits, credits, or access controls.</li>
          <li>Scrape, crawl, or extract data from the Platform through automated means without written permission.</li>
          <li>Use Platform outputs to train competing AI models.</li>
        </ul>

        <h2>4. Subscription Plans and Payments</h2>
        <ul>
          <li>Access to Platform features is governed by your subscription plan (Free, Starter, Professional, Business, or Enterprise).</li>
          <li>Paid subscriptions are billed monthly or annually as selected at the time of purchase.</li>
          <li>Credits are allocated per billing cycle and do not roll over to the next cycle unless your plan specifies otherwise.</li>
          <li>All prices are in Indian Rupees (INR) and exclusive of applicable GST.</li>
          <li>We reserve the right to modify pricing with 30 days&apos; advance notice.</li>
        </ul>

        <h2>5. Intellectual Property</h2>
        <h3>5.1 Your Content</h3>
        <p>
          You retain all rights to contracts and documents you upload. We do not
          claim ownership of your Content. By uploading, you grant us a limited
          licence to process your Content solely to provide the services.
        </p>
        <h3>5.2 Our Platform</h3>
        <p>
          The Platform, including its AI models, software, design, trademarks,
          and documentation, is the intellectual property of LexiDraft
          Technologies. Nothing in these Terms transfers any IP rights to you
          beyond the limited right to use the Platform under your subscription.
        </p>

        <h2>6. AI-Generated Outputs</h2>
        <ul>
          <li>LexiReview&apos;s AI analysis, risk scores, compliance flags, and generated contracts are provided as <strong>decision-support tools</strong>, not legal advice.</li>
          <li>All AI outputs should be reviewed by qualified legal professionals before reliance.</li>
          <li>We do not guarantee the accuracy, completeness, or legal sufficiency of any AI-generated output.</li>
          <li>You are solely responsible for decisions made based on Platform outputs.</li>
        </ul>

        <h2>7. Data Handling</h2>
        <p>
          Your data is handled in accordance with our{" "}
          <Link href="/privacy">Privacy Policy</Link>. Key commitments:
        </p>
        <ul>
          <li>All data stored on servers in India.</li>
          <li>Your documents are not used to train general AI models.</li>
          <li>AES-256 encryption at rest, TLS 1.3 in transit.</li>
          <li>Chain-hashed SHA-256 audit trails for all actions.</li>
        </ul>

        <h2>8. Service Availability</h2>
        <ul>
          <li>We target 99.9% uptime but do not guarantee uninterrupted access.</li>
          <li>Scheduled maintenance will be communicated in advance where practicable.</li>
          <li>We are not liable for downtime caused by force majeure events, third-party service failures, or circumstances beyond our reasonable control.</li>
        </ul>

        <h2>9. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law:
        </p>
        <ul>
          <li>LexiReview is provided &quot;as is&quot; without warranties of any kind, express or implied.</li>
          <li>Our total liability for any claim arising from use of the Platform shall not exceed the fees paid by you in the 12 months preceding the claim.</li>
          <li>We are not liable for indirect, incidental, consequential, or punitive damages.</li>
          <li>We are not liable for losses arising from reliance on AI outputs without independent legal review.</li>
        </ul>

        <h2>10. Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless LexiDraft Technologies, its
          officers, directors, and employees from any claims, losses, or damages
          arising from your use of the Platform, violation of these Terms, or
          infringement of any third-party rights.
        </p>

        <h2>11. Termination</h2>
        <ul>
          <li>You may cancel your subscription at any time through your account settings.</li>
          <li>We may suspend or terminate your account for violation of these Terms, with notice where practicable.</li>
          <li>Upon termination, your right to access the Platform ceases. You may export your data within 30 days of termination.</li>
          <li>Provisions that by their nature should survive termination (IP, liability, indemnification) shall survive.</li>
        </ul>

        <h2>12. Dispute Resolution</h2>
        <ul>
          <li>These Terms are governed by the laws of India.</li>
          <li>Any dispute shall first be attempted to be resolved through good-faith negotiation for 30 days.</li>
          <li>Unresolved disputes shall be referred to arbitration under the Arbitration and Conciliation Act, 1996, with a sole arbitrator, seated in New Delhi.</li>
          <li>The language of arbitration shall be English.</li>
        </ul>

        <h2>13. Modifications to Terms</h2>
        <p>
          We may update these Terms from time to time. Material changes will be
          communicated via email or in-app notification at least 30 days before
          taking effect. Continued use of the Platform after changes take effect
          constitutes acceptance.
        </p>

        <h2>14. General Provisions</h2>
        <ul>
          <li><strong>Severability</strong> — If any provision is held unenforceable, the remaining provisions remain in effect.</li>
          <li><strong>Entire Agreement</strong> — These Terms, together with the Privacy Policy and any applicable subscription agreement, constitute the entire agreement.</li>
          <li><strong>Waiver</strong> — Failure to enforce any provision does not constitute a waiver.</li>
          <li><strong>Assignment</strong> — You may not assign your rights under these Terms without our consent.</li>
        </ul>

        <h2>15. Contact</h2>
        <p>
          For questions about these Terms, contact us at{" "}
          <Link href="mailto:legal@lexireview.in">legal@lexireview.in</Link> or
          visit our <Link href="/contact">Contact page</Link>.
        </p>
      </div>
    </section>
  );
}
