import type {
  RtiApplicationInput,
  RtiApplicationOutput,
} from "@/lib/tools/types";

/**
 * Generates an RTI application per the Right to Information Act, 2005.
 * The application is addressed to the Public Information Officer (PIO)
 * of the relevant public authority. Fee note: ₹10 for non-BPL under
 * Section 7; BPL applicants are exempt under Section 7(5).
 */
export function generateRtiApplication(
  input: RtiApplicationInput
): RtiApplicationOutput {
  const {
    publicAuthorityName,
    publicAuthorityAddress,
    picoDesignation,
    informationSought,
    timePeriod,
    applicantName,
    applicantAddress,
    applicantPhone,
    applicantEmail,
    isBplCategory,
    deliveryMode,
    state,
  } = input;

  const today = new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });

  const feeLine = isBplCategory
    ? `Fee: NIL. I belong to the Below Poverty Line (BPL) category and am exempt from payment of application fee under Section 7(5) of the RTI Act, 2005. A copy of my BPL certificate is enclosed as Annexure A.`
    : `Fee: I am enclosing the application fee of ₹10/- (Rupees Ten only) by way of ${
        deliveryMode === "Email" ? "online payment / IPO" : "Indian Postal Order (IPO)"
      } in favour of "Accounts Officer, ${publicAuthorityName}" as prescribed under Section 6(1) read with the RTI (Regulation of Fee and Cost) Rules, 2005.`;

  const deliveryLine =
    deliveryMode === "Email"
      ? `I request that the information be provided to me by email at ${applicantEmail}.`
      : deliveryMode === "Post"
      ? `I request that the information be provided to me by Registered Post / Speed Post at the address given below. I am willing to pay the postal / photocopy charges as per Rule 4 of the RTI Rules, 2005.`
      : `I will collect the information in person from the office of the Public Information Officer. Kindly intimate me by phone / email when the information is ready.`;

  const text = `
To,
The Public Information Officer${picoDesignation ? ` (${picoDesignation})` : ""},
${publicAuthorityName},
${publicAuthorityAddress}.

Date: ${today}
Place: ${state}

Subject: Application for information under the Right to Information Act, 2005.

Respected Sir / Madam,

Under Section 6(1) of the Right to Information Act, 2005, I, the undersigned, hereby request the following information from your good office:

INFORMATION SOUGHT:
${informationSought}

TIME PERIOD FOR WHICH INFORMATION IS SOUGHT:
${timePeriod}

1. ${feeLine}

2. ${deliveryLine}

3. I certify that the information sought relates to matters of public interest / affects my interest, and I undertake to pay any additional cost of photocopying or further inspection as intimated by your office under Section 7(3).

4. Kindly furnish the information within 30 days from the date of receipt of this application, as mandated under Section 7(1) of the Act. If any part of the information sought is held by another public authority, I request that the application be transferred accordingly under Section 6(3) and I be duly informed.

5. If the Public Information Officer is of the view that any part of the information sought is exempt under Section 8 or Section 9, I request a written, reasoned response specifying the exemption clause relied upon, so that I may exercise my right of first appeal under Section 19.

APPLICANT DETAILS:
Name: ${applicantName}
Address: ${applicantAddress}
Phone: ${applicantPhone}
Email: ${applicantEmail}
Citizenship: Indian

Thanking you,

Yours faithfully,

_________________________
(${applicantName})

Enclosures:
${isBplCategory ? "- BPL certificate (Annexure A)" : "- IPO / Fee receipt of ₹10/-"}
- Self-attested identity proof (optional)

— End of RTI Application —

NOTE: This is an informational template generated by LexiReview under Section 6 of the RTI Act, 2005. Send by Registered Post A.D. or through the online RTI portal (https://rtionline.gov.in) for Central Government public authorities. Retain the acknowledgment. If you do not receive a reply within 30 days, you are entitled to file a First Appeal under Section 19(1) before the First Appellate Authority, and subsequently a Second Appeal / Complaint before the Central or State Information Commission under Section 18 / 19(3).
`.trim();

  return {
    applicationText: text,
    metadata: {
      generatedAt: new Date().toISOString(),
      bpl: isBplCategory,
    },
  };
}
